#:import dp kivy.metrics.dp


<HomeScreen>:

    MDBoxLayout:
        orientation: "vertical"


        MDTopAppBar:
            title: root.store_name
            elevation: 4


        ScrollView:

            MDBoxLayout:
                orientation: "vertical"
                padding: dp(15)
                spacing: dp(15)
                size_hint_y: None
                height: self.minimum_height


                MDLabel:
                    text: "داشبورد حساب‌یار"
                    halign: "center"
                    font_style: "H5"


                MDCard:
                    size_hint_y: None
                    height: dp(120)
                    radius: [20]
                    padding: dp(15)

                    MDBoxLayout:
                        orientation: "vertical"

                        MDLabel:
                            text: "💰 موجودی انبار"

                        MDLabel:
                            text: root.total_inventory



                MDCard:
                    size_hint_y: None
                    height: dp(120)
                    radius: [20]
                    padding: dp(15)

                    MDBoxLayout:
                        orientation: "vertical"

                        MDLabel:
                            text: "🛒 فروش امروز"

                        MDLabel:
                            text: root.today_sales



                MDCard:
                    size_hint_y: None
                    height: dp(120)
                    radius: [20]
                    padding: dp(15)

                    MDBoxLayout:
                        orientation: "vertical"

                        MDLabel:
                            text: "💳 هزینه امروز"

                        MDLabel:
                            text: root.today_expenses



                MDCard:
                    size_hint_y: None
                    height: dp(120)
                    radius: [20]
                    padding: dp(15)

                    MDBoxLayout:
                        orientation: "vertical"

                        MDLabel:
                            text: "📈 سود ماهانه"

                        MDLabel:
                            text: root.monthly_profit





<ProductScreen>:

    MDBoxLayout:
        orientation: "vertical"


        MDTopAppBar:
            title: "کالاها"


        MDTextField:

            hint_text: "جستجوی کالا"

            on_text:

                root.search_products(self.text)



        MDLabel:

            text: "تعداد کالا : " + str(len(root.products))

            halign: "center"




<CustomerScreen>:


    MDBoxLayout:

        orientation: "vertical"


        MDTopAppBar:

            title: "مشتریان"



        MDTextField:

            hint_text: "جستجوی مشتری"

            on_text:

                root.search_customers(self.text)



        MDLabel:

            text: "تعداد مشتری : " + str(len(root.customers))

            halign: "center"





<SaleScreen>:


    MDBoxLayout:

        orientation: "vertical"


        MDTopAppBar:

            title: "ثبت فروش"



        MDLabel:

            text: "ثبت فاکتور فروش"

            halign: "center"





<ExpenseScreen>:


    MDBoxLayout:

        orientation: "vertical"


        MDTopAppBar:

            title: "هزینه‌ها"



        MDLabel:

            text: "ثبت هزینه‌های فروشگاه"

            halign: "center"





<ReportScreen>:


    MDBoxLayout:

        orientation: "vertical"


        MDTopAppBar:

            title: "گزارش‌ها"



        MDLabel:

            text: "گزارش فروش و سود"

            halign: "center"
