#:import dp kivy.metrics.dp


<HomeScreen>:

    MDBoxLayout:
        orientation: "vertical"


        MDTopAppBar:
            title: root.store_name
            elevation: 4


        ScrollView:

            MDBoxLayout:
                orientation: "vertical"
                padding: dp(15)
                spacing: dp(15)
                size_hint_y: None
                height: self.minimum_height


                MDLabel:
                    text: "داشبورد مالی"
                    halign: "center"
                    font_style: "H5"
                    size_hint_y: None
                    height: dp(50)


                MDCard:
                    padding: dp(15)
                    size_hint_y: None
                    height: dp(120)
                    radius: [20]

                    MDBoxLayout:
                        orientation: "vertical"

                        MDLabel:
                            text: "💰 موجودی انبار"

                        MDLabel:
                            text: root.total_inventory


                MDCard:
                    padding: dp(15)
                    size_hint_y: None
                    height: dp(120)
                    radius: [20]

                    MDBoxLayout:
                        orientation: "vertical"

                        MDLabel:
                            text: "🛒 فروش امروز"

                        MDLabel:
                            text: root.today_sales


                MDCard:
                    padding: dp(15)
                    size_hint_y: None
                    height: dp(120)
                    radius: [20]

                    MDBoxLayout:
                        orientation: "vertical"

                        MDLabel:
                            text: "💳 هزینه امروز"

                        MDLabel:
                            text: root.today_expenses


                MDCard:
                    padding: dp(15)
                    size_hint_y: None
                    height: dp(120)
                    radius: [20]

                    MDBoxLayout:
                        orientation: "vertical"

                        MDLabel:
                            text: "📈 سود ماهانه"

                        MDLabel:
                            text: root.monthly_profit



<ProductScreen>:

    MDBoxLayout:
        orientation: "vertical"


        MDTopAppBar:
            title: "کالاها"
            elevation: 4


        MDBoxLayout:
            orientation: "vertical"
            padding: dp(15)
            spacing: dp(15)


            MDTextField:

                hint_text: "جستجوی کالا"

                icon_left: "magnify"

                on_text:
                    root.search_products(self.text)



            MDLabel:

                text: "تعداد کالا: " + str(len(root.products))

                halign: "center"



            MDRaisedButton:

                text: "➕ افزودن کالا"

                pos_hint:
                    center_x: .5

                on_release:

                    root.add_product(
                    "کالای جدید",
                    "000000",
                    0,
                    0,
                    0
                    )



<CustomerScreen>:

    MDBoxLayout:

        orientation: "vertical"

        MDTopAppBar:

            title: "مشتریان"



<SaleScreen>:

    MDBoxLayout:

        orientation: "vertical"

        MDTopAppBar:

            title: "فروش"



<ExpenseScreen>:

    MDBoxLayout:

        orientation: "vertical"

        MDTopAppBar:

            title: "هزینه‌ها"



<ReportScreen>:

    MDBoxLayout:

        orientation: "vertical"

        MDTopAppBar:

            title: "گزارش‌ها"
